artifacts_root: artifacts

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/hotel_reservations.parquet
  val_status: artifacts/data_validation/validation_status.json
  all_schema: config/all_schema.yaml
  validated_data: artifacts/data_validation/hotel_cleaned_data.parquet
  profile_report_name: validated_data_profile.html 