
# RandomForest_params:
#   n_estimators: 100
#   min_samples_split: 2
#   criterion: gini
#   min_weight_fraction_leaf: 0.0
#   max_features: sqrt
#   #random_state: 42





RandomForest_params:
  n_estimators: 150
  min_samples_split: 2
  criterion: gini
  max_features: sqrt
  random_state: 42
  max_depth: 5


  



